apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: rtops
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rtops-api:dev
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rtops-secret
                  key: DATABASE_URL
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rtops-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: rtops-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rtops-secret
                  key: RABBITMQ_PASS
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: rtops-config
                  key: REDIS_URL
