apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: rtops
  labels:
    app: cache
spec:
  selector:
    app: cache
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP