apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmap.yml
  - secret.yml
  - postgres-service.yml
  - postgres-statefulset.yml
  - rabbitmq-service.yml
  - rabbitmq-statefulset.yml
  - cache-service.yml
  - cache-statefulset.yml
  - api-service.yml
  - api-deployment.yml